apiVersion: v1
kind: Service
metadata:
  name: {{ include "flightops.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "flightops.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
